[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
nmap <F7> :NERDTreeToggle

let file_name = expand("%")
if has('vim_starting') && file_name == ""
  autocmd VimEnter * NERDTree ./
endif
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'

# [[plugins]]
# repo = 'nvim-tree/nvim-tree.lua'
# hook_add = '''
# lua << EOF
# vim.g.loaded_netrw = 1
# vim.g.loaded_netrwPlugin = 1
#
# require("nvim-tree").setup()
# EOF
#
# let file_name = expand("%")
# if has('vim_starting') && file_name == ""
#   autocmd VimEnter * NvimTreeOpen ./
# endif
# '''
