[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]]
repo = 'roxma/nvim-yarp'
if = "!has('nvim')"
on_i = 1

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = "!has('nvim')"
on_i = 1

[[plugins]]
repo = 'w0rp/ale'
on_i = 1
hook_post_source = '''
let g:ale_fixers = {
\   'ruby': ['rubocop'],
\}
'''

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['ts']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
